"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 30000

# add_newline = false

# [  ](bg:#a3aed2 fg:#090c0c)\
# $os(bg:#a3aed2 fg:#090c0c)\
format = """
[╭╴](white)\
[░▒▓](#a3aed2)\
$os\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$fill\
$python\
$terraform\
$aws\
$rust\
[](fg:#212736 bg:#1d2230)\
[ ](fg:#1d2230)\
\n\
[╰╴](white)\
$nix_shell\
$character\
"""

[aws]
format = 'on [($profile )(\($region\))(\[$duration\])]($style)'

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 40
style = 'bold yellow'

[fill]
symbol = '—'

[nix_shell]
heuristic = true
symbol = "❄️ "
format = "[$symbol]($style)"

[os]
format = "[ $symbol ]($style)"
style = "bg:#a3aed2 fg:#090c0c"
disabled = false

[os.symbols]
Macos = ""

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[terraform]
format = '[$symbol($version )$workspace]($style) '

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[rust]
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
